### ISSUE TITLE
Multiple groups as "superadmin"

### ISSUE THREAD

**Issue by Megamezzomixer** [GmodAdminSuite/OpenPermissions#2]
I have the following setup: 
Using ULX we have multiple groups above superadmin, like owner and headadmin.
There is no way to set the owner and headadmin group to max privileged.

Currently owner and headadmin do not have access to bLogs' operator tab at all.

**Comment by WilliamVenner** [comment]
yes there is... it's literally right here

https://github.com/GmodAdminSuite/OpenPermissions-Config/blob/master/lua/openpermissions_config.lua

**Comment by Megamezzomixer** [comment]
Uh. Sorry. Literally was desperate and didn't see that,. Thanks.
